title: "CompChem for Newbies"
description: "Learning computational chemistry step by step"
remote_theme: carlosperate/jekyll-theme-rtd   # actively maintained RTD-style theme
markdown: kramdown

# Enable MathJax for LaTeX
kramdown:
  input: GFM
  math_engine: mathjax
  math_engine_opts:
    preview: true

# Declare notebooks as a collection
collections:
  notebooks:
    output: true
    permalink: /notebooks/:name

# Sidebar Navigation
nav:
  - title: "Home"
    url: /
  - title: "Notes"
    children:
      - title: "Introduction"
        url: /notebooks/introduction
      - title: "Basis Sets"
        url: /notebooks/basis_sets
      - title: "Electron Correlation"
        url: /notebooks/correlation
  - title: "XYZ Files"
    url: /xyz/
  - title: "References"
    url: /references/refs.html

# GitHub Pages plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
