title: "CompChem for Newbies"
description: "Learning computational chemistry step by step"
theme: minima
markdown: kramdown

# Enable MathJax for LaTeX support
kramdown:
  input: GFM
  math_engine: mathjax
  math_engine_opts:
    preview: true

# Navigation bar
nav:
  - title: "Home"
    url: /
  - title: "Notes"
    children:
      - title: "Introduction"
        url: /_notebooks/introduction.html
      - title: "Basis Sets"
        url: /_notebooks/basis_sets.html
      - title: "Electron Correlation"
        url: /_notebooks/correlation.html
  - title: "XYZ Files"
    url: /xyz/
  - title: "References"
    url: /references/refs.html

