title: "CompChem for Newbies"
description: "Learning computational chemistry step by step"
baseurl: "/compchem_for_newbies"
remote_theme: carlosperate/jekyll-theme-rtd
markdown: kramdown

# Enable MathJax for LaTeX
kramdown:
  input: GFM
  math_engine: mathjax
  math_engine_opts:
    preview: true

# Declare notebooks as a collection
collections:
  notebooks:
    output: true
    permalink: /notebooks/:name

# Sidebar Navigation
nav:
  - title: "Home"
    url: "/compchem_for_newbies/"
  - title: "Notes"
    children:
      - title: "Introduction"
        url: "/compchem_for_newbies/notebooks/introduction"
      - title: "Basis Sets"
        url: "/compchem_for_newbies/notebooks/basis_sets"
      - title: "Electron Correlation"
        url: "/compchem_for_newbies/notebooks/correlation"
  - title: "XYZ Files"
    url: "/compchem_for_newbies/xyz/"
  - title: "References"
    url: "/compchem_for_newbies/references/refs.html"

# GitHub Pages plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

