title: "CompChem for Newbies"
description: "Welcome! This is a simple GitHub Pages site with notebooks, scripts, images, and references."
theme: minima

# Navigation menu
nav:
  - title: "Home"
    url: /
  - title: "Notebooks"
    url: /notebooks/
  - title: "Scripts"
    url: /scripts/
  - title: "Images"
    url: /images/
  - title: "XYZ Files"
    url: /xyz/
  - title: "References"
    url: /references/

# Enable Markdown + MathJax
markdown: kramdown
kramdown:
  math_engine: mathjax
  input: GFM

